apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml

images:
  - name: dashboard-app
    newName: nstarx.azurecr.io/dashboard-app
    newTag: latest
